### ISSUE TITLE
Uncaught TypeError: _ref1.replace is not a function

### ISSUE THREAD

**Issue by jerone** [jerone/menu-manager#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.0-beta0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [menu-manager](git@github.com:jerone/menu-manager) package, v0.4.3
### Stack Trace

Uncaught TypeError: _ref1.replace is not a function

```
At C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:166

TypeError: _ref1.replace is not a function
    at TreeNode.module.exports.TreeNode.TreeNode.initialize (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:166:64)
    at TreeNode.View [as constructor] (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at new TreeNode (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:19:47)
    at Object.content (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:94:56)
    at Builder.tag (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:281:19)
    at Function.View.(anonymous function) [as ul] (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:83:49)
    at Object.content (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:87:28)
    at Builder.tag (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:281:19)
    at Function.View.(anonymous function) [as li] (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:83:49)
    at Function.module.exports.TreeNode.TreeNode.content (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:32:23)
    at Function.<anonymous> (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:156:31)
    at Function.View.buildHtml (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:123:10)
    at TreeNode.View [as constructor] (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:155:33)
    at new TreeNode (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:19:47)
    at Object.content (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:94:56)
    at Builder.tag (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:281:19)
    at Function.View.(anonymous function) [as ul] (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:83:49)
    at Object.content (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:87:28)
    at Builder.tag (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:281:19)
    at Function.View.(anonymous function) [as li] (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:83:49)
    at Function.module.exports.TreeNode.TreeNode.content (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:32:23)
    at Function.<anonymous> (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:156:31)
    at Function.View.buildHtml (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:123:10)
    at TreeNode.View [as constructor] (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:155:33)
    at new TreeNode (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:19:47)
    at Object.content (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:94:56)
    at Builder.tag (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:281:19)
    at Function.View.(anonymous function) [as ul] (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:83:49)
    at Object.content (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:87:28)
    at Builder.tag (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:281:19)
    at Function.View.(anonymous function) [as li] (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:83:49)
    at Function.module.exports.TreeNode.TreeNode.content (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:32:23)
    at Function.<anonymous> (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:156:31)
    at Function.View.buildHtml (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:123:10)
    at TreeNode.View [as constructor] (C:\Users\jerone\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:155:33)
    at new TreeNode (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:19:47)
    at TreeView.module.exports.TreeView.TreeView.setRoot (C:\Users\jerone\.atom\packages\menu-manager\lib\tree-view.coffee:328:36)
    at C:\Users\jerone\.atom\packages\menu-manager\lib\menu-tree-view.coffee:89:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```
### Commands

```
     -0:07.2.0 open-recent:open-recent-path-6 (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-jade",
      "json-schema"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "menu-manager": {
    "showButton": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-json-editor, v0.4.1
atom-less, v0.1.10
atom-material-syntax, v0.2.10
atom-material-ui, v0.8.0
atom-minify, v0.7.1
bottom-dock, v0.3.7
coffee-refactor, v0.7.0
color-picker, v2.1.0
editorconfig, v1.2.4
file-icons, v1.6.14
flex-tool-bar, v0.7.3
foldername-tabs, v0.1.6
gutter-shadow, v0.6.0
imdone-atom, v1.3.24
indentation-indicator, v0.6.0
jade-autocompile, v0.8.3
language-actionscript3, v0.3.0
language-jade, v0.6.2
less-postcss-autocompile, v1.2.3
less-than-slash, v0.12.1
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-csslint, v1.2.0
linter-htmlhint, v1.0.1
linter-jade, v0.3.2
linter-jshint, v1.2.2
linter-just-say-no, v0.6.0
linter-less, v2.3.3
linter-manager, v0.2.8
linter-markdown, v1.3.0
linter-sass-lint, v0.6.3
linter-scspell, v2.0.1
markdown-scroll-sync, v2.0.3
menu-manager, v0.4.3
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.1
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
new-tab, v0.5.0
open-recent, v4.0.1
pigments, v0.20.0
pinned-tabs, v0.1.10
project-view, v0.4.1
pull-requests, v0.0.16
refactor, v0.6.0
sass-autocompile, v0.12.2
soft-wrap-indicator, v0.7.0
sync-settings, v0.6.0
tool-bar, v0.1.11

# Dev
menu-manager, v0.4.3
new-tab, v0.5.0
sync-settings, v0.6.0
tool-bar, v0.1.11
```

**Comment by jerone** [comment]
https://github.com/Zren/atom-open-recent/issues/16 :arrow_right: https://github.com/lexicalunit/linter-just-say-no/issues/7

**Comment by jerone** [comment]
Workaround in place.
